# Use Ubuntu 22.04 (Jammy) as base image
FROM ubuntu:22.04

# Set noninteractive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install rsync
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    rsync=3.2.7-0ubuntu0.22.04.4 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Verify rsync version
RUN rsync --version

# Set default command
CMD ["rsync", "--version"] 
